name: LeafInventory
version: 2.0.0
author: LeafPixel
main: me.LeafPixel.LeafInventory.LeafInventory
api-version: '1.21'
permissions:
  leafinventory.shulkerbox:
    default: false
  leafinventory.enderchest:
    default: false
  leafinventory.craftingtable:
    default: false
  leafinventory.smithingtable:
    default: false
  leafinventory.stonecutter:
    default: false
  leafinventory.grindstone:
    default: false
  leafinventory.cartographytable:
    default: false
  leafinventory.loom:
    default: false
  leafinventory.anvil:
    default: false
  leafinventory.enchantingtable:
    default: false
  leafinventory.furnace:
    default: false
  leafinventory.blastfurnace:
    default: false
  leafinventory.smoker:
    default: false
